flightgoggles_uav_dynamics:
  init_pose: [0.3, 52.0, 2.5, 0.0, 0.0, -0.707, 0.707]
challenge_name: "Challenge Hard"
timeout: 300.0
gate_names: ['Gate2', 'Gate13', 'Gate9', 'Gate1']
gate_width: 0.3
results_location: "results.yaml"
